export {};

const read = (path: string) => Bun.file(path).text();
const [buildSource, libSource, tauriConfig] = await Promise.all([
  read('src-tauri/build.rs'),
  read('src-tauri/src/lib.rs'),
  Bun.file('src-tauri/tauri.conf.json').json() as Promise<{
    app?: { security?: { capabilities?: string[] } };
  }>,
]);

const buildBlock = buildSource.match(/\.commands\(&\[([\s\S]*?)\]\)/)?.[1] ?? '';
const buildCommands = new Set([...buildBlock.matchAll(/"([a-z][a-z0-9_]*)"/g)].map((match) => match[1]));
const handlerBlock = libSource.match(/generate_handler!\[([\s\S]*?)\]\)/)?.[1] ?? '';
const handlerCommands = new Set([...handlerBlock.matchAll(/(?:\w+::)+(\w+)/g)].map((match) => match[1]));

const capabilityFiles = [
  'src-tauri/capabilities/main-runtime.json',
  'src-tauri/capabilities/settings.json',
  'src-tauri/capabilities/plugin-editor.json',
  'src-tauri/capabilities/plugin-installer.json',
  'src-tauri/capabilities/legal-documents.json',
];
const capabilityCommands = new Set<string>();
const capabilityIdentifiers = new Set<string>();
let mainRuntimePermissions: string[] = [];
for (const file of capabilityFiles) {
  const capability = await Bun.file(file).json() as {
    identifier?: string;
    permissions?: unknown[];
    windows?: string[];
  };
  if (capability.identifier) capabilityIdentifiers.add(capability.identifier);
  if (file.endsWith('main-runtime.json')) {
    mainRuntimePermissions = (capability.permissions ?? []).filter(
      (permission): permission is string => typeof permission === 'string',
    );
  }
  for (const permission of capability.permissions ?? []) {
    if (typeof permission === 'string' && permission.startsWith('allow-')) {
      capabilityCommands.add(permission.slice(6).replaceAll('-', '_'));
    }
  }
}

const permissionFiles = new Bun.Glob('*.toml');
const generatedCommands = new Set<string>();
for await (const file of permissionFiles.scan('src-tauri/permissions/autogenerated')) {
  generatedCommands.add(file.replace(/\.toml$/, ''));
}

const difference = (left: Set<string>, right: Set<string>) =>
  [...left].filter((value) => !right.has(value)).sort();
const failures = [
  ['build.rs only', difference(buildCommands, handlerCommands)],
  ['generate_handler only', difference(handlerCommands, buildCommands)],
  ['missing capability', difference(handlerCommands, capabilityCommands)],
  ['capability without handler', difference(capabilityCommands, handlerCommands)],
  ['missing generated permission', difference(handlerCommands, generatedCommands)],
  ['stale generated permission', difference(generatedCommands, handlerCommands)],
] as const;

const messages = failures
  .filter(([, values]) => values.length > 0)
  .map(([label, values]) => `${label}: ${values.join(', ')}`);
const configuredCapabilities = new Set(tauriConfig.app?.security?.capabilities ?? []);
const missingConfiguredCapabilities = difference(capabilityIdentifiers, configuredCapabilities);
const unknownConfiguredCapabilities = difference(configuredCapabilities, capabilityIdentifiers);
if (missingConfiguredCapabilities.length > 0) {
  messages.push(`capability file not enabled: ${missingConfiguredCapabilities.join(', ')}`);
}
if (unknownConfiguredCapabilities.length > 0) {
  messages.push(`configured capability file missing: ${unknownConfiguredCapabilities.join(', ')}`);
}
const forbiddenMainPermissions = mainRuntimePermissions.filter((permission) =>
  /(?:fs|shell|updater|dialog|opener|create)/i.test(permission)
  || /allow-(?:install|uninstall|get-installed|load-plugin-for-edit|save-plugin|export-plugin)/.test(permission)
);
if (forbiddenMainPermissions.length > 0) {
  messages.push(`dangerous main-runtime permission: ${forbiddenMainPermissions.join(', ')}`);
}
const expectedMainCommands = new Set([
  'log_to_file',
  'update_menu_state',
  'set_menu_item_enabled',
  'set_active_bookstore',
  'set_title',
  'toggle_stealth',
  'toggle_menu_bar',
  'simulate_menu_click',
  'switch_bookstore_by_index',
  'apply_site_zoom',
  'get_app_name',
  'get_settings',
  'patch_settings',
  'get_reading_position',
  'save_reading_position',
  'get_runtime_plugin',
]);
const mainCommands = new Set(
  mainRuntimePermissions
    .filter((permission) => permission.startsWith('allow-'))
    .map((permission) => permission.slice(6).replaceAll('-', '_')),
);
const missingMainCommands = difference(expectedMainCommands, mainCommands);
const unexpectedMainCommands = difference(mainCommands, expectedMainCommands);
if (missingMainCommands.length > 0) {
  messages.push(`main-runtime missing command: ${missingMainCommands.join(', ')}`);
}
if (unexpectedMainCommands.length > 0) {
  messages.push(`main-runtime unexpected command: ${unexpectedMainCommands.join(', ')}`);
}
if (messages.length > 0) {
  console.error(`IPC consistency check failed:\n${messages.join('\n')}`);
  process.exit(1);
}
console.log(`IPC consistency verified for ${handlerCommands.size} commands.`);
